import "dart:io";
import "dart:typed_data";

import "package:intl/intl.dart";
import "package:path_provider/path_provider.dart";
import "package:pdf/pdf.dart";
import "package:pdf/widgets.dart" as pw;
import "../models.dart";

class PdfReportService {
  Future<Uint8List> buildSalesReport(PosSalesReport report) async {
    final document = pw.Document();
    final currency = NumberFormat.currency(symbol: "\$", decimalDigits: 2);
    final generatedAt = DateFormat("dd MMM yyyy HH:mm").format(DateTime.now());

    document.addPage(
      pw.MultiPage(
        pageTheme: const pw.PageTheme(
          pageFormat: PdfPageFormat.a4,
          margin: pw.EdgeInsets.all(24),
        ),
        build: (context) => [
          pw.Text(
            "WHITE ANGELS APPARELS",
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            "Sales Report",
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            "Period: ${_prettyDate(report.from)} - ${_prettyDate(report.to)}",
          ),
          pw.SizedBox(height: 16),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            children: [
              _summaryRow(
                "Total Revenue",
                currency.format(report.summary.totalRevenue),
              ),
              _summaryRow("Transactions", report.summary.salesCount.toString()),
              _summaryRow("Units Sold", report.summary.unitsSold.toString()),
              _summaryRow(
                "Average Sale",
                currency.format(report.summary.averageSale),
              ),
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Text(
            "Sales",
            style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            headers: const ["Date", "Sale No.", "Units", "Amount"],
            data: report.sales
                .map(
                  (sale) => [
                    DateFormat("dd MMM yyyy HH:mm").format(sale.soldAt),
                    sale.saleNumber,
                    sale.totalUnits.toString(),
                    currency.format(sale.totalAmount),
                  ],
                )
                .toList(),
            cellStyle: const pw.TextStyle(fontSize: 9),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: 10,
            ),
            border: pw.TableBorder.all(color: PdfColors.grey300),
            cellAlignment: pw.Alignment.centerLeft,
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey100),
          ),
        ],
        footer: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Divider(color: PdfColors.grey400),
            pw.Text(
              "Generated by White Angels POS",
              style: const pw.TextStyle(fontSize: 9),
            ),
            pw.Text(
              "Generated: $generatedAt",
              style: const pw.TextStyle(fontSize: 9),
            ),
          ],
        ),
      ),
    );

    return document.save();
  }

  String buildFileName(PosSalesReport report) =>
      "white-angels-sales-${report.from}-to-${report.to}.pdf";

  Future<String> saveReport(Uint8List bytes, String fileName) async {
    final directory = await getApplicationDocumentsDirectory();
    final file = File("${directory.path}/$fileName");
    await file.writeAsBytes(bytes, flush: true);
    return file.path;
  }

  pw.TableRow _summaryRow(String label, String value) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(
            label,
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
        ),
        pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(value)),
      ],
    );
  }

  String _prettyDate(String value) {
    final parsed = DateTime.tryParse(value);
    if (parsed == null) return value;
    return DateFormat("dd MMM yyyy").format(parsed);
  }
}
