name: white_angels_pos
description: "White Angels POS companion application."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  fl_chart: ^1.1.1
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  provider: ^6.1.5+1
  share_plus: ^11.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/white-angels-logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/white-angels-logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/white-angels-logo.png
